### ISSUE TITLE
Add a virtual package for WordPress core?

### ISSUE THREAD

**Issue by gmazzap** [johnpbloch/wordpress#5] opened 2015-02-25 21:04 UTC
At the moment, best way to have WordPress sites entirely managed with Composer is to use this package.

And according to [Packagist stats](https://packagist.org/search/?q=wordpress), it's also the _de facto_ standard way to do that.

So, first of all, **thanks**.

Today, for first time, I've worked on a package that make sense to use **only** in WordPress sites **entirely** managed via Composer.

So I thought was fine to state in `composer.json` it  _requires_ WordPress.

Now, once WordPress has not it's own official Composer package, at least not yet, the only way to do that would be to add `johnpbloch/wordpress` among the dependencies of my package.

I have nothing against your name :), but that doesn't seem right to me.

In fact, my package can work with **any**  composer package that provides WordPress, so requiring your specific package I think it's wrong. 

This is the reason IMO it worth to start using a virtual package `"wordpress/wordpress"` by adding it to [`provide` setting](https://getcomposer.org/doc/04-schema.md#provide) of this package.

That way, packages intended to be used in sites entirely managed via Composer, can add that virtual package in their `require` setting.

And that requirement will be satisfied by your package or by any other package that will declare to provide WordPress.

If [one day WordPress will natively support Composer](https://core.trac.wordpress.org/ticket/23912), all packages that had declared a dependency from "wordpress/wordpress" will continue to work without any change.

Opinions?

**Comment by johnpbloch** [comment] 2015-02-25 21:43
:+1: for the proposal in general (rely on abstractions instead of concretions). I will have to think about the specific proposal of using `"wordpress/wordpress"` as the virtual package name. I'm inclined to say we should use something else.

My main concern comes from uncertainty about how `"provides"` works. For example if my site requires *my* WP package and your package (which requires the virtual package), should core release a package w/ the same name as the virtual package, will my site now require 2 instances of core?

**Comment by mnapoli** [comment] 2015-02-25 21:56
I think it shouldn't use `wordpress/wordpress` if this is not the official repository.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-25 22:39
@mnapoli Problem is it doesn't exist any official repository. And who knows if it will ever exist. That's why I'm suggesting to use that name in `provide` (not as the package name).

I think this repo is the only one that has the numbers to establish a standard for a virtual WordPress alias.

I've suggested `wordpress/wordpress` because in the official trac ticket that's the name that was proposed by @rarst (2 years ago) for a WordPress official package. I don't know if you're familiar with WordPress trac system, but things can stay open there for decades...

Surely, we can use a different name for the virtual package, but in that case **if** WordPress will ever officially support Composer all the packages that had required that virtual package need to be updated. Unless WP itself will also embrace that virtual package name invented by us, and that's not exactly easy.

@johnpbloch I'm not 100% sure, but I thinks that, yes, in that case your site will require 2 instances of core, unless that official release contains a [`replace`](https://getcomposer.org/doc/04-schema.md#replace) link to your package.

If you want I can do some tests... (in the weekend).

However, consider that normally virtual packages are used for packages that doesn't really exists, if core will ever release a *real* package named `wordpress/wordpress` you should probably remove the `provide` entry in your composer.json...

And I would say that in case of official WordPress Composer support, this package will not make a lot of sense anymore...and you could mark it as "abandoned" in Packagist (or completely remove it) after having also marked it as replaced by official core package...

**Comment by mnapoli** [comment] 2015-02-25 23:27
> That's why I'm suggesting to use that name in provide (not as the package name).

Oh clever!

**Comment by johnpbloch** [comment] 2015-02-25 23:33
I plan to continue updating this package from upstream until nobody is using it any more. Even if core releases an official composer package.

> if WordPress will ever officially support Composer all the packages that had required that virtual package need to be updated.

Only if the providing package is gone. In which case they'd need to update their composer manifest anyway, since non-existent packages are un-meetable dependencies. This, to me, is highly preferable to maybe accidentally installing a second copy of core which could have quite unexpected consequences (as there's no way of knowing what a composer.json file would look like in core).

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-25 23:42
> as there's no way of knowing what a composer.json file would look like in core

Of course that's the biggest problem.

If I understand well your opinion is:

 - option 1: do nothing
 - option 2: let's use something that isn't `wordpress/wordpress`

I prefer the second, but I'll survive the first :) and I'd love some other people opinion.

**Comment by johnpbloch** [comment] 2015-02-26 00:14
My opinion is option 2 and only option 2. Using virtual packages is a great idea and I love it and it should definitely happen.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-26 00:29
Nice. Let's see I can persuade you.

Let's assume we use `wordpress/wordpress` as virtual name.

If and when WordPress will release official Composer package you can replace `provide` with [`conflict`](https://getcomposer.org/doc/04-schema.md#conflict).

That way a double core installation will be never possible and so people will be forced to switch from this package to official one. When no one use this anymore, you can just delete it from Packagist.

Note that when you remove a package from Packagist there there is the possibility to declare a package that replaces it.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-26 00:33
Moreover, if people store their `composer.lock` file  (that's pivotal in whole site Composer packages) they will be able to recreate their exact site state even if the switch from `provide` to `conflict` had happened meanwhile.

**Comment by Rarst** [comment] 2015-02-26 10:42
Against.

`wordpress/*` vendor “belongs” to the WordPress project. It is pointless to make assumptions about it and outright problematic (in regards to unknown future) to actually use it.

While the situation isn't _optimal_, in my opinion it's _acceptable_. I think `suggest` block is perfectly passable option to recommend _some_ version of WordPress package.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-26 11:48
@Rarst there is no doubt that `wordpress/*` belongs to WordPress project, but IMO that has nothing to do with the fact that we may or not may use it in the **`provide`** block.

IMO `provide` make perfectly sense for things that you **don't** own, just like `suggest` and `conflict`. Even in the Composer docs they are all listed under "package links". And "link" don't implies ownership.

In real world, one of the most used `provide` usage is for PSR log. I counted [14 packages](https://packagist.org/providers/psr/log-implementation) that uses `psr/log-implementation` and no one of them `own` PSR namespace.

Of course, in the outside-of-WordPress world, `provide` is used for interfaces, and not for  implementations. However, to use Composer in WordPress we *already* do things that outside-of-WordPress people don't do for the simple reason that WP, as project, don't support Composer.

BTW I'm still fine with not using `wordpress/wordpress` but I think that if there is a standard for packages that *provides* WordPress (in the lack of WordPress provides itself), it will be a good thing for us as WP developers.

Finally, what should we use in the `suggest` block? `johnpbloch/wordpress`?

Let's assume a newbie user followed a tutorial on the internet that explains how to setup a custom WordPress Composer package (You know there are some). And then they requires a package that suggests `johnpbloch/wordpress`. If they adds  `johnpbloch/wordpress`, as suggested, they now has 2 versions of WordPress core.

Should we suggest `wordpress/wordpress`? It's doable, but how sense it makes suggesting something that doesn't exists neither as virtual package?

**Comment by Rarst** [comment] 2015-02-26 11:53
Interesting, do you have a backstory and reasoning on `psr/log-implementation` ? Quick google didn't come up with anything but that page on Packagist.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-26 12:03
I remember something I read on the topic, but can't find the article.

Summary is that being a set common interfaces, if in my packages I uses only methods from those interfaces (via DI) I can make use of any package that implements them, no need to require a *specific* implementations.

Only posts I found regarding the argument are:

 - https://devedge.wordpress.com/2014/09/27/composer-and-virtual-packages/
 - http://php-and-symfony.matthiasnoback.nl/2014/10/composer-provide-and-dependency-inversion/

the latter is pretty against the usage of `provide`, but at the end of the article he opens to some usage cases

**Comment by johnpbloch** [comment] 2015-02-26 16:27
That's a good point that none of the packages providing `psr/log-implementation` own the psr vendor name. I'm all for using the wordpress vendor name.

However, to continue using that example, they also didn't claim to provide `psr/log` while PSR-3 was being voted on, nor (I imagine) would they sit idly by if FIG started discussing whether they should release a package named `psr/log-implementation`.

For virtual packages, it makes the most sense to *me* to use a name that more directly implies the virtual/general nature of the virtual package. If I saw someone using `wordpress/wordpress` I would assume it was an actual core package, not a virtual one. Something like `wordpress/wordpress-implementation` or `wordpress/wordpress-core-package` strikes me as much less confusing.

So two things:

1. `wordpress/wordpress` is totally out of the question in my mind if a core package being released would cause 2 copies of WP to be installed.
1. If only one copy of WP gets installed with no unexpected behavior, **what are the pros and cons** of using `wordpress/wordpress`? What are the pros and cons of using a more generalized virtual package name?

I'll work on some tests to see what happens in the scenario of a core package coming out.

**Comment by Rarst** [comment] 2015-02-26 16:40
One other point I want to raise is that it might be WordPress environment _without WordPress package_. For example I have a mixed kind of install where some plugins are managed by Composer, but WordPress core is "normal" and manages itself.

Making core a hard requirement in some form would prevent package from working in such kind of install.

Overall I feel this is bit of a solution in search of a problem. The only thing we can't do right now is to require specific version of core package, that _essentially doesn't actually exist anyway_.

Is it so _important_ of an issue to start piling up hacks to address it? It's not broken. :)

**Comment by johnpbloch** [comment] 2015-02-26 16:54
Real quick, set up a test for what happens when a provided package gets added as a non-virtual one: https://gist.github.com/johnpbloch/b325aa2e93d92100c80d

Results: 3rd package gets installed as normal but doesn't interfere with providing package either.

**Comment by Giuseppe-Mazzapica** [comment] 2015-02-26 17:20
@johnpbloch don't forget that **`conflict`** can be used to avoid 2 copies of WP to be installed in any case.

Regarding pros and cons I think that most of them are related to a future WordPress implementation of Composer. And once there is no way to know how it will ever be IMO is just matter of personal preference. And I don't actually have one: `wordpress/wordpress` or `wordpress/wordpress-implementation` or `wordpress/whatever` let me know what I've to use and I'll use it :)

@Rarst 

> Making core a hard requirement in some form would prevent package from working in such kind of install.

Of course. In my 1st post I said that it make sense **only** on packages intended to be used in sites **entirely** managed via Composer. And it's up to developer of the package add a require or not. And developer (should) know if it's the case. 

BTW, even though I am pretty prolific I never wrote (untill yesterday) something like that :)

So, no, I don't think it is *so important*.

However, if we add a `provide` here it will not hurt this package nor any other packages, actually it will have no effect on the great majority of packages. But for the small part of packages that **requires** a full WordPress environment, being able to require WordPress will be -at least- interesting.

**Comment by QWp6t** [comment] 2015-04-23 09:26
It seems like this is mostly a cosmetic thing, with you not wanting to use the johnpbloch namespace.

I'm unconvinced that this is necessary, but to each his own. Meh.

**Comment by johnpbloch** [comment] 2015-04-23 13:51
@QWp6t I'm not getting the vibe that it's a cosmetic preference. I think it's more about flexibility in use. Virtual packages are a pretty useful feature of composer and one that (I think) fits the bill here.

Not strictly *necessary*, but still useful to some people without affecting anybody who doesn't want to use it.

**Comment by dzuelke** [comment] 2017-01-30 03:49
... so? :) I'd love it if this package provided `wordpress/wordpress`, too =)

**Comment by johnpbloch** [comment] 2017-08-16 13:48
I just submitted a PR to add this to the build routine: https://github.com/johnpbloch/build-wp/pull/3

Please take a look and add your comments over there.

**Comment by johnpbloch** [comment] 2017-08-18 16:12
This has been added to the build script and the docker containers have been rebuilt. This will make its way into master within an hour and into the next round of tags/branches that get released. The virtual package is `wordpress/core-implementation`, and it is `johnpbloch/wordpress-core` that provides it, not this package.

**Closed by johnpbloch** 2017-08-18 16:12 UTC
